### ISSUE TITLE
GitHub user access cleanup

### ISSUE THREAD

**Issue by dougwilson** [jshttp/jshttp.github.io#67]
Hi @jshttp/owners, I'm working on auditing the current owners of the jshttp organization. If any of you think you don't need to actually be an owner, please let me know as a comment here or by email and I can remove you (I also think you have the ability to remove yourself).

I'm also going to be demoting the current owners that do not have 2FA on their GitHub account to just members of the organization for now. If you are affected, and want to be promoted back to an owner, please let me know 1) that you have setup 2FA on your GitHub account or 2) why you can't enable it (perhaps there is a legitimate reason).

**Comment by defunctzombie** [comment]
I don't think I need to be an owner. If I have continued contributions I will open PRs :)

**Comment by dougwilson** [comment]
Thanks for the response, @defunctzombie ! I'm leaning some more still about all the new settings, as there are so many now :) I have converted you to an "outside collaborator", which I think in general just means jshttp is just another GitHub org to you. Let me know if you wanted to be something else, as I don't intend to make any changes you don't want :)
